#!/usr/bin/env python3
"""
Copy the currently published images back from the live site so a deploy can
happen without re-rendering (site-only deploys: HTML/CSS/JS changes, tropical
or plumes refreshes). Reads every manifest listed in site/config.js for this
repo's own base ("" or matching SITE_URL) and downloads the referenced PNGs.

    SITE_URL=https://user.github.io/repo/ python render/restore_live.py
"""
from __future__ import annotations

import json
import logging
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
log = logging.getLogger("restore")
ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"


def main():
    site = os.environ.get("SITE_URL", "").rstrip("/") + "/"
    if not site.startswith("http"):
        log.error("SITE_URL not set"); sys.exit(1)
    session = requests.Session()
    # which manifests does this site serve? default manifest.json plus any manifest-*.json named in config.js
    names = {"manifest.json"}
    cfg = (SITE / "config.js").read_text() if (SITE / "config.js").exists() else ""
    for m in re.finditer(r'manifest:\s*"([^"]+)"', cfg):
        names.add(m.group(1))
    urls = []
    for name in sorted(names):
        try:
            r = session.get(site + name, timeout=30, headers={"Cache-Control": "no-cache"})
            if r.status_code != 200:
                continue
            man = r.json()
            (SITE / name).write_text(json.dumps(man, indent=1))
            model = man["model"]["id"]
            for run in man["model"]["runs"]:
                for region in run["regions"]:
                    for pid in run["params"]:
                        hours = (run.get("param_hours") or {}).get(pid, run["hours"])
                        for h in hours:
                            urls.append(man["path"].format(model=model, run=run["id"], region=region, param=pid, hour=f"{h:03d}"))
            log.info("%s: %s, %d runs", name, model, len(man["model"]["runs"]))
        except Exception as e:  # noqa: BLE001
            log.info("%s not on live site (%s)", name, e)
    # tropical + plumes assets are regenerated by their own steps; just images/mjo cache helps
    def fetch(rel):
        dest = SITE / rel
        if dest.exists():
            return True
        dest.parent.mkdir(parents=True, exist_ok=True)
        for _ in range(3):
            try:
                r = session.get(site + rel, timeout=60)
                if r.status_code == 200:
                    dest.write_bytes(r.content); return True
                if r.status_code == 404:
                    return False
            except requests.RequestException:
                pass
        return False
    with ThreadPoolExecutor(max_workers=16) as ex:
        got = sum(1 for ok in ex.map(fetch, urls) if ok)
    log.info("restored %d/%d images from the live site", got, len(urls))


if __name__ == "__main__":
    main()
